#
# Application name and list of source files.
#
NAME=axis2align2
CCSRCS=main.cpp


#
# Dependency libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg  -lpng -lm 

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


