#
# Application name and list of source files.
#
# Function: given flat file to visualize mesh2D and mesh3D
NAME=prp2persistence
CCSRCS=main.cpp Region.cpp RegionMerger.cpp


#
# Dependency libraries
#

PKG_LIBS=-lRNExt -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg  -lpng -lm -lANN

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


