#
# Application name and list of source files.
#
# Function: given flat file to visualize mesh2D and mesh3D
NAME=check_axis_consistency
CCSRCS=main.cpp


#
# Dependency libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg  -lpng -lm 

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


