# Package name and list of source files.

NAME=BasicNumerical
CCSRCS=	Calculus.cpp \
	LinAlgVectorReal.cpp \
	LinAlgVectorComplex.cpp \
	LinAlgMatrixReal.cpp \
	LinAlgMatrixComplex.cpp \
	las2.cpp \
	svdlib.cpp \
	svdutil.cpp \
	LinAlgComplex.cpp


#LinAlgMatrixSparseReal.cpp \
#EXT_LIBS = gsl CXSparse UFconfig
#PKG_LIBS = -lgsl -lm -lgslcblas
#PKG_INCS=-I/usr/local/include/
include ../../makefiles/Makefile.pkgs
